#include "Bus.h"

namespace DataStructure {




Bus* Bus::getInstance()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-15-40-112--6564ad52:1616f2ac498:-8000:000000000000090C begin
{
}
// section 10-15-40-112--6564ad52:1616f2ac498:-8000:000000000000090C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace DataStructure */
