#include "GUI/MainFrame.h"


namespace GUI {

MainFrame::MainFrame(Parser::Configuration* conf){
	nana::size s(conf->getResolutionX(), conf->getResolutionY());
	size(s);
	move(-10, 0);
}

void MainFrame::onBusUpdate(){

}
// section 10-15-40-112--6564ad52:1616f2ac498:-8000:0000000000000914 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace GUI */
