#include "GUI/MainFrame.h"

namespace GUI {




void MainFrame::onBusUpdate()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-15-40-112--6564ad52:1616f2ac498:-8000:0000000000000914 begin
{
}
// section 10-15-40-112--6564ad52:1616f2ac498:-8000:0000000000000914 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace GUI */
